# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/groupChat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/groupChat.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proto/groupChat.proto\x12\x04grpc\"\x1e\n\nClientInfo\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"(\n\x03Msg\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\x05\x42lank\x12\x10\n\x08received\x18\x01 \x01(\x08\x32`\n\x0fGroupChatServer\x12*\n\tmsgStream\x12\x10.grpc.ClientInfo\x1a\t.grpc.Msg0\x01\x12!\n\x07SendMsg\x12\t.grpc.Msg\x1a\x0b.grpc.Blankb\x06proto3'
)




_CLIENTINFO = _descriptor.Descriptor(
  name='ClientInfo',
  full_name='grpc.ClientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='grpc.ClientInfo.clientId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=61,
)


_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='grpc.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='grpc.Msg.clientId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc.Msg.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=103,
)


_BLANK = _descriptor.Descriptor(
  name='Blank',
  full_name='grpc.Blank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='received', full_name='grpc.Blank.received', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['ClientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['Blank'] = _BLANK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'proto.groupChat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'proto.groupChat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Msg)
  })
_sym_db.RegisterMessage(Msg)

Blank = _reflection.GeneratedProtocolMessageType('Blank', (_message.Message,), {
  'DESCRIPTOR' : _BLANK,
  '__module__' : 'proto.groupChat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Blank)
  })
_sym_db.RegisterMessage(Blank)



_GROUPCHATSERVER = _descriptor.ServiceDescriptor(
  name='GroupChatServer',
  full_name='grpc.GroupChatServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=132,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='msgStream',
    full_name='grpc.GroupChatServer.msgStream',
    index=0,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendMsg',
    full_name='grpc.GroupChatServer.SendMsg',
    index=1,
    containing_service=None,
    input_type=_MSG,
    output_type=_BLANK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GROUPCHATSERVER)

DESCRIPTOR.services_by_name['GroupChatServer'] = _GROUPCHATSERVER

# @@protoc_insertion_point(module_scope)
