# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import groupChat_pb2 as proto_dot_groupChat__pb2


class GroupChatServerStub(object):
    """Service for sending msgs history stream to new client and sending new msgs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.msgStream = channel.unary_stream(
                '/grpc.GroupChatServer/msgStream',
                request_serializer=proto_dot_groupChat__pb2.ClientInfo.SerializeToString,
                response_deserializer=proto_dot_groupChat__pb2.Msg.FromString,
                )
        self.SendMsg = channel.unary_unary(
                '/grpc.GroupChatServer/SendMsg',
                request_serializer=proto_dot_groupChat__pb2.Msg.SerializeToString,
                response_deserializer=proto_dot_groupChat__pb2.Blank.FromString,
                )


class GroupChatServerServicer(object):
    """Service for sending msgs history stream to new client and sending new msgs
    """

    def msgStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupChatServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'msgStream': grpc.unary_stream_rpc_method_handler(
                    servicer.msgStream,
                    request_deserializer=proto_dot_groupChat__pb2.ClientInfo.FromString,
                    response_serializer=proto_dot_groupChat__pb2.Msg.SerializeToString,
            ),
            'SendMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMsg,
                    request_deserializer=proto_dot_groupChat__pb2.Msg.FromString,
                    response_serializer=proto_dot_groupChat__pb2.Blank.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.GroupChatServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GroupChatServer(object):
    """Service for sending msgs history stream to new client and sending new msgs
    """

    @staticmethod
    def msgStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.GroupChatServer/msgStream',
            proto_dot_groupChat__pb2.ClientInfo.SerializeToString,
            proto_dot_groupChat__pb2.Msg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.GroupChatServer/SendMsg',
            proto_dot_groupChat__pb2.Msg.SerializeToString,
            proto_dot_groupChat__pb2.Blank.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
